exports.users = require('./users')
exports.courses = require('./courses')
exports.instances = require('./instances')
exports.invitations = require('./invitations')
exports.recurrings = require('./recurrings')
exports.userPreset = require('./userPreset')